In [7]:
! pip install numpy
import numpy as np
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.6 MB 5.2 MB/s eta 0:00:03
   ----- ---------------------------------- 1.8/12.6 MB 6.7 MB/s eta 0:00:02
   ------------- -------------------------- 4.2/12.6 MB 6.4 MB/s eta 0:00:02
   ---------------- ----------------------- 5.2/12.6 MB 7.1 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.6 MB 7.0 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.6 MB 7.1 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.6 MB 7.3 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 7.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 7.3 MB/s eta 0:00:00
[1 2 3 4 5]


In [8]:
import numpy as np
my_array = np.arange(7, 100, 3)
print(my_array)

[ 7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76
 79 82 85 88 91 94 97]


In [9]:
my_array = np.random.uniform(low=0.0, high=1.0, size=(6, 6))
print(my_array)

[[0.1749804  0.17882494 0.63435299 0.73005989 0.45333251 0.9630468 ]
 [0.52962452 0.7365819  0.3027157  0.57303256 0.37492469 0.44537227]
 [0.87251049 0.03903683 0.49056052 0.20536238 0.36105374 0.80473547]
 [0.88942735 0.12517333 0.15718802 0.42649939 0.18374806 0.41195896]
 [0.54392193 0.18553963 0.81723339 0.11986192 0.72413909 0.37560969]
 [0.04305189 0.54039216 0.88970925 0.35751651 0.74664031 0.85597764]]


In [10]:
mean = 2.0
std_dev = 1.0
size = (6, 6)

my_array = np.random.normal(loc=mean, scale=std_dev, size=size)

print(my_array)

[[2.08603784 1.84139395 1.74707466 2.74318101 2.63546383 2.62650178]
 [3.20447982 1.51747032 3.66892608 3.09111822 1.79049911 2.20471928]
 [3.07940013 2.70884802 2.42130511 2.48187531 3.32236664 2.39915824]
 [2.75280106 2.47421745 3.02715724 2.6417898  2.33802462 3.53183928]
 [3.39415973 1.08057402 0.54547243 3.77331429 1.39567522 1.99342007]
 [0.30174274 2.04243374 3.66109423 2.54077228 3.69498526 2.91629873]]


In [11]:
a = np.zeros((5,5),)
a[2][2] = 1

print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
a = np.zeros((5,5),)
for i in range(5):
    if i % 2 == 0:
        for k in range(5):
            a[i][k] = 1

print(a)

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


In [14]:
a = np.zeros((5,5),)
for i in range(5):
    if i % 2 == 0:
        for k in range(5):
            if k % 2 == 0:
                a[k][i] = 1

print(a)

[[1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1.]
 [0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1.]]


In [17]:
a = np.ones((3,3),)
a[1][1] = 9

for i in range(3):
    for j in range(3):
        if a[i][j] == 9:
            a[i][j] = 18
print(a)

[[ 1.  1.  1.]
 [ 1. 18.  1.]
 [ 1.  1.  1.]]


In [19]:
a = np.ones((4,4),)
j = 2
while j != 4:
    for i in range(3):
        a[j][i] = 9
    j += 1

for i in range(4):
    for j in range(4):
        if a[i][j] == 9:
            a[i][j] = 18
print(a)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [18. 18. 18.  1.]
 [18. 18. 18.  1.]]


In [22]:
a = np.ones((6,6),)
j = 2
while j != 4:
    i = 2
    while i != 4:
        a[j][i] = 9
        i += 1
    j += 1

for i in range(6):
    for j in range(6):
        if a[i][j] == 9:
            a[i][j] = 18
print(a)

[[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1. 18. 18.  1.  1.]
 [ 1.  1. 18. 18.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]


EXERCISE. Given an image as a Numpy array of shape (5,5,3), representing image's width and height
of 5 pixels and 3 channels: Red, Green, Blue.
Write a preprocess() function to process image with the following steps:
Check the input image size, if it's not (5,5,3), raise an error.
Make a copy of the input image so that changes won't affect original data.
Crop the copied image to the center so that the final result is 3x3x3 (get center values only)
This image will be fed into a deep learning model, which requires another dimension for batch.
Therefore, you need to add 1 dimension to the image so that the final shape is (1,3,3,3)
Return a dictionary contain these following info:
"image": the processed image,
"shape": the processed image's shape,
"dims" : the string "multiple" if the number of dimension is > 1, otherwise, the string "single",
"n_elements": number of elements of the processed image.

In [29]:
import random
colors = ['Red', 'Green', 'Blue']
img = np.array(
    [
        [colors, colors, colors, colors, colors],
        [colors, colors, colors, colors, colors],
        [colors, colors, colors, colors, colors],
        [colors, colors, colors, colors, colors],
        [colors, colors, colors, colors, colors]
    ]
)

def preprocess(ar):
    if ar.shape != (5, 5, 3):
        print("An error has been occurred!")
    ar1 = ar.copy()
    ar1 = ar1[1:4,1:4,0:3]
    ar1 = ar1.reshape((1,3,3,3))
    a = ar1.shape
    b = ar1.ndim
    c = ar1.size
    if b == 1:
        b = single
    dct = { "image": ar1,
            "shape": a,
            "dims" : b,
            "n_elements": c
        }
    return dct

img2 = preprocess(img)
print(img2)

{'image': array([[[['Red', 'Green', 'Blue'],
         ['Red', 'Green', 'Blue'],
         ['Red', 'Green', 'Blue']],

        [['Red', 'Green', 'Blue'],
         ['Red', 'Green', 'Blue'],
         ['Red', 'Green', 'Blue']],

        [['Red', 'Green', 'Blue'],
         ['Red', 'Green', 'Blue'],
         ['Red', 'Green', 'Blue']]]], dtype='<U5'), 'shape': (1, 3, 3, 3), 'dims': 4, 'n_elements': 27}


Exercise 2.
a. Create a 1D array and sum all its elements, then find the max, min values.
b. Create a 2D array and sum all elements, find the max, min values along rows.
c. Create a 2D array and sum all elements, find the max, min, values along
columns.
d. Write a NumPy program to create a 3x3 matrix with values ranging
from 2 to 10.
e. Write a NumPy program to reverse an array (the first element becomes
the last).

In [37]:
# a)
import random
import numpy as np

a = np.zeros(10,)
for k in range(10):
    a[k] = random.randint(10, 20)
print(a)
min = a.min(axis=0)
print(f"min is {min}")
max = a.max(axis=0)
print(f"min is {max}")
sum = np.sum(a)
print(f"the sum is {sum}")

# b)
b = np.ones((4, 4),)
for k in range(4):
    for j in range(4):
        b[k][j]= random.randint(10, 20)
print(b)
min = b.min(axis=0)
print(f"min is {min}")
max = b.max(axis=0)
print(f"min is {max}")
sum = np.sum(b)
print(f"the sum is {sum}")

# c)
c = np.zeros((4, 4),)
for k in range(4):
    for j in range(4):
        c[k][j]= random.randint(10, 20)
print(c)
min = c.min(axis=1)
print(f"min is {min}")
max = c.max(axis=1)
print(f"min is {max}")
sum = np.sum(c)
print(f"the sum is {sum}")

# d)
d = np.ones((3, 3),)
for k in range(3):
    for j in range(3):
        d[k][j]= random.randint(2, 10)
print(d)

# e)
e = np.zeros(10,)
for j in range(10):
        e[j]= random.randint(10, 20)
print(e)
e = np.flip(e)
print(e)


[12. 15. 11. 18. 16. 11. 17. 17. 14. 20.]
min is 11.0
min is 20.0
the sum is 151.0
[[18. 20. 12. 20.]
 [10. 14. 19. 14.]
 [13. 12. 15. 12.]
 [12. 15. 10. 12.]]
min is [10. 12. 10. 12.]
min is [18. 20. 19. 20.]
the sum is 228.0
[[19. 14. 14. 19.]
 [14. 12. 13. 19.]
 [10. 12. 16. 12.]
 [14. 18. 20. 11.]]
min is [14. 12. 10. 11.]
min is [19. 19. 16. 20.]
the sum is 237.0
[[ 5.  7.  6.]
 [10.  5. 10.]
 [ 5.  6.  8.]]
[16. 16. 11. 11. 15. 11. 10. 19. 11. 14.]
[14. 11. 19. 10. 11. 15. 11. 11. 16. 16.]
